version: "3.9"

services:
  access_control:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /home/wifelly/projects/ass_c/qr/:/app/qr
    environment:
      - LITESTAR_AUTO_RELOAD=true

  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
